---
name: Damian Świstowski
email: damian@swistowski.org
phone: "+44 7402 64 28 69"
github: https://github.com/dswistowski/dswistowski.github.io
linkedin: https://www.linkedin.com/in/dswistowski/

about_me:
  - >
    I am software developer with 15+ years of experience in the industry. I
    have worked on a wide range of projects, from small web applications to
    large enterprise systems. I am a polyglot programmer, but I have a
    particular interest in python, typescript and distributed systems.
work:
  - date: "Oct 2023-Oct 2024"
    title: "Software Engineer"
    where: "Genie AI"
    city: "Remote"
    description:
      - >
        Developed backend services with a focus on enhancing testability.
      - >
        Automated continuous delivery pipeline and streamlined building dependencies process.
      - >
        Integrated with multiple exchanges and blockchains including Deribit, OKX and Solana.
      - >
        Expanded asset metric portfolio ensuring efficient calculation methods.

    stack:
      - python
      - fastapi
      - kubernetes
      - terraform
      - postgresql
      - typescript
      - react
      - graphql
      - rest api

  - date: "2022-2023"
    title: "Staff Engineer"
    where: "Babylon Health"
    city: "London"
    description:
      - >
        Designed and constructed the 3rd generation of the Babylon conversation platform for asynchronous messaging.
      - >
        Developed GraphQL API for northbound traffic and Rest API for east-west traffic.
      - >
        Create Conversation Platform Test Runner, a tool for defining requirements and tests in Domain Specific
        Language. COPteR provides an abstraction to have stable acceptance tests for the whole product, with
        fraction-less integration with Babylon testing infrastructure.

    stack:
      - python
      - fastapi
      - kubernetes
      - elasticsearch
      - kafka
      - typescript
      - react native
      - graphql
      - rest api

  - date: "2020-2022"
    title: "Engineering Manager"
    where: "Babylon Health"
    city: "London"
    description:
      - >
        Managed 3-6 direct reports, adapting to team size.
      - >
        Collaborated with stakeholders and product managers to define roadmap and priorities.
      - >
        Successfully replaced 1st generation Babylon conversation platform with 2nd generation seamlessly.
      - >
        Ensured strict compliance with SSDLC and best practices within the team.
      - >
        Advocated for a balanced workload to prevent technical debt accumulation.
      - >
        Aligned team deliverables with client requirements through rigorous oversight.
      - >
        Conducted knowledge-sharing pairing sessions with team members.

    stack:
      - python
      - flask
      - kubernetes
      - terraform
      - postgres
      - redis
      - kafka
      - typescript
      - rest api

  - date: "2019-2000"
    title: "Senior Software Engineer"
    where: "Babylon Health"
    city: "London"
    description:
      - >
        Designed migration plan from 1st generation monolith to 2nd generation microservices for Babylon conversation platform
      - >
        Developed CLI tools to facilitate integration with the Conversation Platform for internal and external teams.

    stack:
      - python
      - flask
      - kubernetes
      - terraform
      - postgresql
      - redis
      - kafka
      - rest api

  - date: "2019"
    title: "Senior Software Engineer"
    where: "B2C2"
    city: London
    description:
      - >
        Created the Trade History collecting system
      - >
        Implemented REST API crawler as cloud task and processed raw data using stateless procedures
      - >
        Integrated with multiple exchange APIs
        

    stack:
      - python
      - aws
      - lambda
      - sqs
      - elasticache

  - date: "2017-2019"
    title: "Senior Python Developer"
    where: "Springer Nature"
    city: London
    description:
      - >
        Built and improved internal CI/CD system and tools
      - >
        Managed migration of legacy code to Python3
      - >
         Defined build pipelines for other teams with simplified build steps
      - >
        Created tooling for Cloud Foundry deployments

    stack:
      - python
      - OpenStack
      - CloudFoundry
      - celery

  - date: "2015-2017"
    title: "Senior Engineer"
    where: "Shortlist"
    city: San Francisco (remote)
    description:
      - >
        Developed backend for the workforce management platform project.
      - >
        Collaborated with frontend engineers to create a functional REST API.
      - >
        Designed and implemented a data model for the system.

    stack:
      - python
      - django
      - postgresql
      - django rest framework
      - javascript
      - angular
      - rest api

  - date: "2012-2015"
    title: "Senior Python Developer"
    where: "ZedMedia"
    city: Globally (remote)
    description:
      - >
        Maintained a Django-based applications.
      - >
        Implemented a scoring algorithm for articles to be displayed in a different section of the service.
      - >
        Extended and maintained database models.
      - >
        Developed tools to facilitate A/B testing.

    stack:
      - python
      - django
      - postgresql
      - javascript
      - perl

  - date: "2010-2012"
    title: "Senior Python Developer"
    where: "Intelligent Elite"
    city: Barcelona
    description:
      - >
        Developed an A/B testing suite with in-depth user behavior statistics.
      - >
        Enhanced the mailing system.

    stack:
      - python
      - django
      - postgresql
      - solr
      - mongodb

  - date: "2008-2010"
    title: "Python Developer"
    where: "OMS"
    city: Bielsko-Biała, Poland
    description:
      - >
        Design and implement a production management system
      - >
        Managing a team of 4 junior engineers

    stack:
      - python
      - django
      - mysql

  - date: "2007-2008"
    title: "PHP Junior developer"
    where: "Gery Design"
    city: Wrocław, Poland
    description:
      - >
        Migrate old PHP projects to the Django framework
      - >
        Maintenance and optimization of existing projects

    stack:
      - php
      - javascript
      - python
      - django
      -
education:
  - place: The University of Silesia
    city: Katowice
    faculty: Computer Science and Materials Science
    date: 2005 - 2007
    what: Master of Computer Science
    thesis: Particle Swarm Optimization in funding function minimum
  - place: The University of Silesia
    city: Katowice
    faculty: Computer Science and Materials Science
    date: 2002 - 2005
    what: Bachelor of Computer Science
    thesis: Developing an electronic repository for undergraduate theses

publications:
  - title: "Comparative Study: ACO and EC for TSP"
    date: 2006
    journal: kaeiog
    abstract: The paper concentrates on the Traveling Salesman Problem solved by evolutionary and ACO algorithms
    asset: kaeiog

talks:
  - where: PyCon UK
    title: c?attrs how use it with rest microservices
    presentation: https://debonair-mitten.surge.sh/
    url: https://www.youtube.com/watch?v=jkq-p6H85Rs
    date: 2019

interests:
  - Hiking
  - Social dancing
  - Cooking
  - Video Games
